### ISSUE TITLE
constant cache tracing?

### ISSUE THREAD

**Issue by alepore** [simeonwillbanks/busted#17]
Hi!
I wonder if it would be possibile to also have _constant_ cache invalidation locations via dtrace, or if there's some kind of limitation.
I have this situation on some old rails apps and i'm not sure how to solve:

<img width="388" alt="screen shot 2016-10-15 at 16 29 50" src="https://cloud.githubusercontent.com/assets/557414/19411100/f59f6904-92fa-11e6-87e4-67f906ab771d.png">

Thanks!

**Comment by alepore** [comment]
related: https://github.com/ruby/ruby/pull/1462

**Comment by simeonwillbanks** [comment]
@alepore Good call sending a Pull Request to Ruby.  _Busted_ [uses the dtrace capabilities](https://github.com/simeonwillbanks/busted/blob/ff71bc079e0233970ed7959f3e2ed48cedb1e43f/dtrace/probes/busted/method-cache-clear.d#L5) from [Ruby which don't include constant cache traces](http://ruby-doc.org/core-2.3.1/doc/dtrace_probes_rdoc.html). 😄 

Is it OK to close this issue?  Thanks!

**Comment by alepore** [comment]
Sure!

**Comment by simeonwillbanks** [comment]
Good luck and thanks!
